a = int(input("Enter the first number"))
b = int(input("Enter the second number"))
c = int(input("Enter the third number"))
d = int(input("Enter the fourth number"))
x = (a + b) / (c + d)
x = float('{:.2f}'.format(x))
print(x)